# Base Prometheus configuration - shared by all deployments
# This reduces duplication across multiple compose files
version: '3.8'

x-prometheus-base: &prometheus-base
  image: ${PROMETHEUS_IMAGE:-docker.io/prom/prometheus:v2.47.0}
  container_name: prometheus-dev
  hostname: prometheus-dev
  restart: unless-stopped
  volumes:
    - prometheus-data:/prometheus
  command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=7d'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    - '--web.enable-lifecycle'
  networks:
    - monitoring
  healthcheck:
    test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s
  mem_limit: 1g
  cpus: 1.0

# Base network configuration
networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24

# Base volume configuration
volumes:
  prometheus-data:
    labels:
      project: "prom-dev"
      component: "prometheus"
